services:

  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    ports:
      - "9090:8080"  
      - "7077:7077"  
    environment:
      - SPARK_MODE=master
    volumes:
      - ../../data:/home/jovyan/data
      - ../../src:/home/jovyan/work
      - ./spark-logs:/spark-logs
      - ../../ignore/jars:/home/jovyan/jars
      - ../../ignore:/home/jovyan/ignore
    networks:
      - spark-network

  worker-1:
    image: bitnami/spark:3.5.0
    container_name: worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ../../data:/home/jovyan/data
      - ../../src:/home/jovyan/work
      - ./spark-logs:/spark-logs
      - ../../ignore/jars:/home/jovyan/jars
      - ../../ignore:/home/jovyan/ignore
    networks:
      - spark-network

  worker-2:
    image: bitnami/spark:3.5.0
    container_name: worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"  
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ../../data:/home/jovyan/data
      - ../../src:/home/jovyan/work
      - ./spark-logs:/spark-logs
      - ../../ignore/jars:/home/jovyan/jars
      - ../../ignore:/home/jovyan/ignore
    networks:
      - spark-network

  spark-history-server:
    image: bitnami/spark:3.5.0
    container_name: spark-history
    depends_on:
      - spark-master
    ports:
      - "18080:18080"  
    volumes:
      - ./spark-logs:/spark-logs
    networks:
      - spark-network
  
  pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ../../data:/home/jovyan/data
      - ../../src:/home/jovyan/work
      - ./spark-logs:/spark-logs
      - ../../ignore/jars:/home/jovyan/jars
      - ../../ignore:/home/jovyan/ignore
    command: start-notebook.py --NotebookApp.token=''
    networks:
      - spark-network

networks:
  spark-network:
    name: spark-network
    driver: bridge
