services:
  flink-jobmanager:
    image: apache/flink:1.19.0-scala_2.12-java17
    container_name: flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    volumes:
      - G:/Files/Files Docker/BGD-Projects:/BGD-Projects/Flink/JobManager
      - G:/Files/Files Docker/BGD-Projects:/BGD-Projects/Flink/TaskManager
    command: jobmanager

  flink-taskmanager:
    image: apache/flink:1.19.0-scala_2.12-java17
    container_name: flink-taskmanager
    expose:
      - "6121"
    volumes:
      - G:/Files/Files Docker/BGD-Projects:/BGD-Projects/Flink/JobManager
      - G:/Files/Files Docker/BGD-Projects:/BGD-Projects/Flink/TaskManager
    command: taskmanager

networks:
  spark-network:
    driver: bridge