services:
  postgres:
    image: postgres:16
    container_name: pgsql
    environment:
      POSTGRES_DB: pgsql
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql123
    ports:
      - "5436:5432"
    volumes:
      - ./pgsdata:/var/lib/postgresql/data

